### ISSUE TITLE
Cookiecutters are missing the upgrade-python-requirements.yml GitHub Action

### ISSUE THREAD

**Issue by timmc-edx** [openedx/edx-cookiecutters#251]
A/C:

- The base `python-template` cookiecutter includes the action
- The action doesn't notify anyone by default
- The "do this after creation" checklist (in the cookiecutter's own README) includes modifying the Action to notify person/group

**Comment by aht007** [comment]
Done in: https://github.com/openedx/edx-cookiecutters/pull/260
