### ISSUE TITLE
Improve Dockerfile for Django IDA cookiecutter

### ISSUE THREAD

**Issue by iamsobanjaved** [openedx/edx-cookiecutters#292]
### Parent Issue: https://github.com/openedx/devstack/issues/943

As we have been improving the native Dockerfile in all of our existing IDAs which are being used in devstack. So we should update the Dockerfile of Django IDA cookie-cutter so that all newly created IDAs should have this functionality out of the box. 

The Dockerfile of the IDA should have the following things:
- Ensure that the repo's Dockerfile can create a base image that is appropriate for small production installations
- Ensure that the repo's Dockerfile also defines an additional image derived from the base which adds dependencies and configuration changes needed for development environments
- Automate uploads of both images when code changes are merged

Dockerfile: https://github.com/openedx/edx-cookiecutters/blob/master/cookiecutter-django-ida/%7B%7Bcookiecutter.repo_name%7D%7D/Dockerfile

**Comment by jmbowman** [comment]
I ran into this one during Innovation Week.  https://github.com/edx/flashcards/blob/main/Dockerfile was my quick attempt at this for a single new service (that needed Python 3.9 for a specific dependency), might be useful for reference.
