### ISSUE TITLE
Change to `production-requirements` target in django-ida Makefile

### ISSUE THREAD

**Issue by timmc-edx** [openedx/edx-cookiecutters#384]
A/C

- [ ] All Django IDA Makefiles now use "production-requirements" instead of prod_requirements
- [x] The Django IDA cookie cutter creates Makefiles with "production-requirements" as a target

The django-ida cookiecutter includes a `prod_requirements` Makefile target, but the configuration repo expects `production-requirements`: https://github.com/openedx/configuration/blob/354249b7b0ef7e5c74656e340449fa1e38156658/playbooks/roles/edx_django_service/tasks/main.yml#L168

I don't think we had a particular principled reason to use `prod_requirements`, and the string doesn't appear anywhere other than in Makefiles, probably generated by the cookiecutter: https://github.com/search?type=code&q=(org%3Aopenedx+OR+org%3Aedx)+prod_requirements+NOT+path%3AMakefile (or possibly in whatever Makefile was abstracted from to make the django-ida cookiecutter)

We should probably change this in the cookiecutter and update repos.

**Comment by dianakhuang** [comment]
Other than the cookiecutter fix, which has been merged, I've made the PRs against the repos and informed the owning teams, so I am going to close this ticket now.

**Comment by dianakhuang** [comment]
@grmartin I have not been able to do any testing. It's possible that teams will have to do other fixes if they need to get the Makefile to work in particular environments.

**Comment by timmc-edx** [comment]
Oof, yeah, we probably need to declare a dependency on `piptools` as well -- the target calls `pip-sync` but there's no guarantee that pip-tools has been installed yet. -.-
