### ISSUE TITLE
Ci build fails for xblock

### ISSUE THREAD

**Issue by Talha-Rizwan** [openedx/edx-cookiecutters#411]
Hi,
I recently created an openedx xblock using the edx-cookiecutter template but turns out the github actions ci.yml is failing at this stage

```
- name: Create Build
      run: |
        rm -rf /tmp/myxblock-xblock
        XBLOCK=$(pwd) && cd /tmp/ && echo -e '\n\n\n\n\n' | cookiecutter $XBLOCK
        cd /tmp/myxblock-xblock && make help && pip install -e .
        cd /tmp/myxblock-xblock && make dev.build

```
Error:

```
-> Run rm -rf /tmp/myxblock-xblock
/home/runner/work/_temp/54fcbeee-2c42-4109-b7e4-76c22b1b61fa.sh: line 2: cookiecutter: command not found
Error: Process completed with exit code 127.
```
I also installed the cookiecutter in the ci but the build still failed with the following error:

```
A valid repository for "/home/runner/work/openedx-cmi5-xblock/openedx-cmi5-xblock" could not be found in the following locations:
/home/runner/work/openedx-cmi5-xblock/openedx-cmi5-xblock
/home/runner/work/openedx-cmi5-xblock/openedx-cmi5-xblock
Error: Process completed with exit code 1.
```

This is happening from the very first commit since the template xblock got created and make upgrade didn’t help either.

Once you eliminate this Build step and perform certain necessary linting corrections in the template xblock, the workflow passes all the checks.

You can also discuss this issue [here](https://discuss.openedx.org/t/ci-build-fails-for-a-new-cookiecutter-xblock/11784)

**Comment by rgraber** [comment]
Acceptance Criteria:

- [ ] Review https://github.com/openedx/edx-cookiecutters/issues/411

**Comment by rgraber** [comment]
The acceptance criteria have been updated to fixing the CI issues. Ended up closing the initial PR and splitting the work into multiple new ones:
https://github.com/openedx/edx-cookiecutters/pull/423
https://github.com/openedx/edx-cookiecutters/pull/424
https://github.com/openedx/edx-cookiecutters/pull/425
https://github.com/openedx/edx-cookiecutters/pull/426
https://github.com/openedx/edx-cookiecutters/pull/428
