### ISSUE TITLE
Update edx-cookie-cutter

### ISSUE THREAD

**Issue by farhan** [openedx/edx-cookiecutters#460]
Update edx-cookie-cutter

- Deprecate [xblock-utils](https://github.com/openedx/edx-cookiecutters/blob/master/cookiecutter-xblock/%7B%7Bcookiecutter.repo_name%7D%7D/requirements/base.in#L8) package
- Also need to update Python & Django versions and Github Actions are also outdated.

**Comment by irtazaakram** [comment]
Also need to update Python & Django versions and Github Actions are also outdated.
